---
- name: Install required packages
  loop:
    - lsb-release
    - figlet
    - update-motd
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - motd

- name: Disable defined files
  loop: "{{ motd_disable }}"
  loop_control:
    label: "/etc/update-motd.d/{{ item }}"
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  tags:
    - motd

- name: Write defined files
  loop: "{{ motd_files }}"
  loop_control:
    label: "/etc/update-motd.d/{{ item.dest }}"
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "/etc/update-motd.d/{{ item.dest }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - motd

...
