- name: install packages
  loop:
    - lsb-release
    - figlet
    - update-motd
  package:
    name: '{{ item }}'
    state: present
  tags:
     - motd

- name: disable files
  loop: '{{ motd_disable }}'
  loop_control:
    label: '/etc/update-motd.d/{{ item }}'
  file:
    path: '/etc/update-motd.d/{{ item }}'
    state: absent
  tags:
     - motd

- name: write files
  loop: '{{ motd_files }}'
  loop_control:
    label: '/etc/update-motd.d/{{ item.dest }}'
  template:
    src: '{{ item.template }}'
    dest: '/etc/update-motd.d/{{ item.dest }}'
    mode: u=rwx,g=rx,o=rx
  tags:
     - motd
